task: segmentation
num_classes: 2
image_size: [512, 512]

# GPU otimizado (RunPod A40/A100)
batch_size: 8
epochs: 100
learning_rate: 0.001
num_workers: 4
amp: true

train_manifest: ./datasets/processed/manifests/train_manifest.json
val_manifest: ./datasets/processed/manifests/val_manifest.json
checkpoint_name: segmentation_best.pt
